### ISSUE TITLE
How to change "press hold time" programmatically

### ISSUE THREAD

**Issue by tony-wallace** [OpenWonderLabs/python-host#10]
I think this is related to issue #7 

My Switchbot needs to hold a button down for 8 sec or more to shut down a device. 
The same Switchbot needs to hold the same button down for 5 sec or less to power up the device. 
If the Press hold time is set long enough to shut down the device, then the Switchbot can not power up the device; the device will simply stay down.  

It would be great if the Switchbot API could be made available for those who would like to extend this program. 
Thank you.

**Comment by nemccarthy** [comment]
@tony-wallace  I've started a project to allow you to get more details on the switchbots, currently this project supports passwords and getting the battery and firmware version. You can find the support here: https://github.com/nemccarthy/pySwitchbot/

The aim is to merge this project into HomeAssistant. 

I've been able to find the press time setting string. The next step is to try setting this programatically. Let me know if youre still interested in this and I'll add it in.

**Comment by tony-wallace** [comment]
[x] Get and set long press time settings

Yes, please. I have been using a remote-control power strip in combination with the Switchbots. It would be helpful if the power strip was not absolutely required. 

Thanks!

**Comment by Chanete** [comment]
[x] Get and set long press time settings 

Same here. I use the smartswitch to control my heating system remotely. Some times, I need to reset the device and this is made by pressing the power button for 5 secs.  I've tried using the ON and OFF commands, but all of them do the same!!! 

So, changing the press time will solve my issue!  Thx.

**Comment by nicolas-kuechler** [comment]
I built a REST / Python API which allows to control the following switchbot functionality both in encrypted and unencrypted mode:

- actions: press, turn on, turn off 
- get settings: battery, firmware, number of timers, mode, hold time
- set settings: hold time, mode
- timers: get timers, set timers, sync timers

You can find the code here: https://github.com/nicolas-kuechler/switchbot

If you want to build your own library you can check out the documentation of the BLE API at the end of the README. It should contain most of the information that you need.

**Comment by SwitchBot-Wonderlabs** [comment]
Bot has pressing time setting in the APP.
In addition, the action sequence version has also been released.
If needed, you can feedback in the app.
Thanks.
