### ISSUE TITLE
Can't scan the SwitchBot.

### ISSUE THREAD

**Issue by hwangjr** [OpenWonderLabs/python-host#13]
I run the script:
```
sudo python switchbot.py
Usage: "sudo python switchbot.py [mac_addr  cmd]" or "sudo python switchbot.py"
Start scanning...
scan timeout
No SwitchBot nearby, exit
```

Raspberry Pi 4 with Bluetooth 5.5. 
SwitchBot S1, FCC ID:2AKXBS1

**Comment by thepiam** [comment]
Same thing happened to me, scan always timed out.
But when I specified BLE MAC and a command it worked, like so:

sudo python python-host/switchbot.py C6:F2:0E:A1:86:70 Turn On
sudo python python-host/switchbot.py C6:F2:0E:A1:86:70 Turn Off
sudo python python-host/switchbot.py C6:F2:0E:A1:86:70 Up
sudo python python-host/switchbot.py C6:F2:0E:A1:86:70 Down
sudo python python-host/switchbot.py C6:F2:0E:A1:86:70 Press

**Comment by hwangjr** [comment]
@thepiam  yep, but I can't get the address without scanning the device. (except connect to the phone to get the address first)

**Comment by Thomasbomb** [comment]
I believe this is due to a firmware update on the switchbot. Someone should see if they can update it to work with the new firmware. I might if I end up buying one

**Comment by hwangjr** [comment]
seems no one care about this. I already buy 10+ SwitchBots...

**Comment by hwangjr** [comment]
@SwitchBot  any progress for this issue?

**Comment by nicolas-kuechler** [comment]
@hwangjr
What firmware version do your bots have? (you can find the information with the official app)

You can try my api which relies on another python ble library:
https://github.com/nicolas-kuechler/switchbot 

After setting up the python environment as described in the readme, the code below (must be run with sudo) should find the switchbots:

```python
from switchbot import Scanner

scanner = Scanner()
mac_addresses = scanner.scan(known_dict={})
```

My code is tested with firmware version 4.5 and a raspberry pi 3.

**Comment by hwangjr** [comment]
@nicolas-kuechler  ok, I will have a try. thx
