### ISSUE TITLE
ImportError: No module named bluepy.btle

### ISSUE THREAD

**Issue by amccombsahce** [OpenWonderLabs/python-host#15]
**I am having trouble with this, even though I installed bluepy, the switchbot.py cannot find it**

pi@raspberrypi:~/python-host` $ python switchbot.py

Traceback (most recent call last):
  File "switchbot.py", line 17, in <module>
    from bluepy.btle import Scanner, DefaultDelegate
ImportError: No module named bluepy.btle

**but I already did the bluepy install and it shows here:**

pi@raspberrypi:~/python-host $ sudo pip3 install bluepy

Requirement already satisfied: bluepy in /usr/local/lib/python3.5/dist-packages

**Comment by amccombsahce** [comment]
got it to work

**Comment by dev4light** [comment]
How did you got it to work?

**Comment by sampath97** [comment]
@amccombsahce  I am facing the same issue. How did you got it to work?

**Comment by amccombsahce** [comment]
I think I uninstalled pip3 and python3, rebooted and reinstalled.
