### ISSUE TITLE
Curtain support?

### ISSUE THREAD

**Issue by daenny** [OpenWonderLabs/python-host#18]
I have the switchbot curtain. I wondered if that is already supported by this library?

**Comment by scstraus** [comment]
I also wonder that. It doesn't appear to really be mentioned here anywhere but they link to this repo as the place where the API should be provided. 

I also wonder how you are meant to access the API via the gateway.. Neither of these things are clearly documented anywhere that I can see.

**Comment by masterfish1** [comment]
I would hope it includes the curtain; it was specifically mentioned on the Kickstarter page. https://www.kickstarter.com/projects/switchbot/switchbot-curtain-make-your-curtains-smart-in-seconds/description

Being able to integrate this with Home Assistant was a big sales point for me.

**Comment by scstraus** [comment]
I wrote them on the kickstarter page and they said they were planning it for later in the year.

**Comment by djdevil** [comment]
@SwitchBot  hello any news?

**Comment by scstraus** [comment]
I would remind them on the kickstarter page that we are waiting for it.. That seems to be the only place they watch.

**Comment by daenny** [comment]
https://github.com/SwitchBot/homebridge-switchbot-ble/

It seems that they released a Homebridge plugin in typescript. 
I would love to see support in python as well.

**Comment by SwitchBot-Wonderlabs** [comment]
Hi, @daenny , try the latest commit.

**Comment by daenny** [comment]
Thanks! all working fine!
