### ISSUE TITLE
Can i get the firmware and battery level

### ISSUE THREAD

**Issue by masato-ka** [OpenWonderLabs/python-host#7]
The Driver can get firmware version and battery?
i want to manage the SwitchBot.

**Comment by nemccarthy** [comment]
@masato-ka I've started a project to allow you to get the battery and firmware version. You can find the support here: https://github.com/nemccarthy/pySwitchbot/tree/batt-support

The aim is to merge this project into HomeAssistant.

**Comment by masato-ka** [comment]
Thank you. I check the branch.
